name: safe_banking_app
description: "A Flutter application providing information about safe banking practices and information about the banks in the country of Czechia."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.2.20

flutter:
  uses-material-design: true
  assets:
    - assets/data/banks.json
    - assets/images/george_logo.png
    - assets/images/cs_logo_bg.png
    - assets/images/kb.png
    - assets/images/ab.png
    - assets/images/flutter.png
    - assets/images/logo.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"